name: 🐞 Reportar um Problema
description: Informe um problema técnico ou de configuração.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - prestabr
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para preencher este formulário!
  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Versão da PrestaShop?
      options:
        - PS 1.6.x
        - PS 1.7.x
        - PS 8.x
        - PS 9.x
    validations:
      required: true
  - type: dropdown
    id: php
    attributes:
      label: Versão do PHP?
      options:
        - PHP 5.x
        - PHP 6.x
        - PHP 7.x
        - PHP 8.x
    validations:
      required: true
  - type: dropdown
    id: Severity
    attributes:
      label: Qual é a gravidade do problema?
      multiple: true
      options:
        - Não consegui instalar o modulo
        - Não consegui configurar o modulo
        - Nenhum cliente consegue fazer pagamentos
        - Uma das opções pagamentos não está funcionando
    validations:
      required: true

