name: ❓ Estou com Dúvidas
description: Para questões técnicas, dúvidas de configuração ou solicitações comerciais.
title: "[Question]: "
labels: ["question", "documentation","Needs Triage"]
assignees:
  - prestabr
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para preencher este formulário!
  - type: input
    id: contact
    attributes:
      label: E-mail de contato
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Qual é a sua dúvida, como podemos ajudar?
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Versão da PrestaShop
      options:
        - PS 1.6
        - PS 1.7
        - PS 8.0
    validations:
      required: true