name: ❓ Estou com Dúvidas
description: Para questões técnicas, dúvidas de configuração ou solicitações comerciais.
title: "[Question]: "
labels: ["question", "documentation","Needs Triage"]
assignees:
  - prestabr
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para preencher este relatório de dúvidas!
  - type: input
    id: contact
    attributes:
      label: Dados de Contato
      description: Como podemos contatá-lo se precisarmos de mais informações?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Qual a sua dúvida?
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Versão da PrestaShop
      description: Qual a versão da sua loja?
      options:
        - PS 1.6
        - PS 1.7
        - PS 8.0
    validations:
      required: true